### PR TITLE
Refactor agent setup guide

### PR DESCRIPTION
**Pull request by sarah256**
This PR aims to improve the agent's documentation.

[Link to GH Pages site](https://jellyfish-ai.github.io/jf_agent/index.html)

### CODE REVIEW

**Review by mattklein — APPROVED** [review]
Love this! Made a few further tweaks in a separate commit...

**Review by daviskeene — APPROVED** [review]
Looks great! Only nit that I have would be to re-phrase the `validate` run mode description to something more like:

**Comment by jnicoleoliveira** [comment]
The opening comment, I think could use a few tweaks.
> Welcome to the JF Agent Documentation! The agent is a tool used to connect to your systems to give you back metrics and other data to help your organization. If you are looking to set up your agent for the first time, see here.

I'm not the greatest at copy.. so maybe even this could use some help.
> Welcome to the JF Agent Documentation! The agent is an on-premise configuration tool you can use to send data to Jellyfish in order to power the metrics and insights that will help your organization. You can use this documentation to guide you in setting up, or troubleshooting.

**Comment by sarah256** [comment]
As per https://jelly-ai.slack.com/archives/CPERQK8TV/p1625665714233400 decided to merge GH pages work

**Pull request merged**
